name: Deploy to Dreamhost

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Clean install dependencies
        run: npm ci
      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug Build Output
        run: ls -R dist

      - name: Deploy to Dreamhost
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/miami-valley-xpress/"
          REMOTE_HOST: ${{ secrets.DREAMHOST_HOST }}
          REMOTE_USER: ${{ secrets.DREAMHOST_USER }}
          TARGET: "/home/dh_8v69cj/miamivalleyxpress.com/"
