name: Deploy to Dreamhost

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Dreamhost
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: pdx1-shared-a2-01.dreamhost.com
          REMOTE_USER: dh_8v69cj
          SOURCE: "dist/"
          TARGET: "/home/dh_8v69cj/miamivalleyxpress.com"
